# Form implementation generated from reading ui file '.\exit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Exit(object):
    def setupUi(self, Exit):
        Exit.setObjectName("Exit")
        Exit.resize(300, 300)
        Exit.setMinimumSize(QtCore.QSize(300, 300))
        Exit.setMaximumSize(QtCore.QSize(300, 300))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Exit)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.time = QtWidgets.QLabel(parent=Exit)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.time.setFont(font)
        self.time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time.setObjectName("time")
        self.verticalLayout_2.addWidget(self.time)
        self.count = QtWidgets.QLabel(parent=Exit)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.count.setFont(font)
        self.count.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.count.setObjectName("count")
        self.verticalLayout_2.addWidget(self.count)
        self.speed = QtWidgets.QLabel(parent=Exit)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.speed.setFont(font)
        self.speed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.speed.setObjectName("speed")
        self.verticalLayout_2.addWidget(self.speed)
        self.accuracy = QtWidgets.QLabel(parent=Exit)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.accuracy.setFont(font)
        self.accuracy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accuracy.setObjectName("accuracy")
        self.verticalLayout_2.addWidget(self.accuracy)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exit = QtWidgets.QPushButton(parent=Exit)
        self.exit.setAutoDefault(False)
        self.exit.setObjectName("exit")
        self.horizontalLayout.addWidget(self.exit)
        self.restart = QtWidgets.QPushButton(parent=Exit)
        self.restart.setAutoDefault(False)
        self.restart.setObjectName("restart")
        self.horizontalLayout.addWidget(self.restart)
        self.cancel = QtWidgets.QPushButton(parent=Exit)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Exit)
        QtCore.QMetaObject.connectSlotsByName(Exit)

    def retranslateUi(self, Exit):
        _translate = QtCore.QCoreApplication.translate
        Exit.setWindowTitle(_translate("Exit", "Выход"))
        self.time.setText(_translate("Exit", "время"))
        self.count.setText(_translate("Exit", "сиволы"))
        self.speed.setText(_translate("Exit", "скорость"))
        self.accuracy.setText(_translate("Exit", "точность"))
        self.exit.setText(_translate("Exit", "Выйти"))
        self.restart.setText(_translate("Exit", "Перезапуск"))
        self.cancel.setText(_translate("Exit", "Продолжить"))
