# Form implementation generated from reading ui file '.\training.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Train(object):
    def setupUi(self, Train):
        Train.setObjectName("Train")
        Train.resize(800, 600)
        Train.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Train)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progress_bar = QtWidgets.QProgressBar(parent=Train)
        self.progress_bar.setMinimumSize(QtCore.QSize(0, 0))
        self.progress_bar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.progress_bar.setStyleSheet("\n"
"QProgressBar{\n"
"    background-color :black;\n"
"    border : 1px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: yellow;\n"
"    border : 1px;\n"
"}")
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progress_bar.setInvertedAppearance(False)
        self.progress_bar.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.frame_2 = QtWidgets.QFrame(parent=Train)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.timer = QtWidgets.QLabel(parent=self.frame_2)
        self.timer.setMaximumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timer.setFont(font)
        self.timer.setToolTipDuration(0)
        self.timer.setStyleSheet("border: 8px solid;\n"
"border-radius: 15px;\n"
"border-color: rgb(70, 70, 70);\n"
"padding: 5px;\n"
"\n"
"background-color: rgb(255, 255, 255);")
        self.timer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.timer.setIndent(0)
        self.timer.setObjectName("timer")
        self.horizontalLayout.addWidget(self.timer)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=Train)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setLineWidth(10)
        self.frame.setMidLineWidth(100)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_box = QtWidgets.QWidget(parent=self.frame)
        self.text_box.setAcceptDrops(False)
        self.text_box.setObjectName("text_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.text_box)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.left = QtWidgets.QLabel(parent=self.text_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left.sizePolicy().hasHeightForWidth())
        self.left.setSizePolicy(sizePolicy)
        self.left.setMinimumSize(QtCore.QSize(100, 0))
        self.left.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.left.setFont(font)
        self.left.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.left.setAutoFillBackground(False)
        self.left.setStyleSheet("color: rgb(75, 75, 75);\n"
"background-color: rgb(211, 211, 211);\n"
"\n"
"margin-right: -500px;\n"
"padding-top: 8px;\n"
"padding-bottom: 8px;\n"
"\n"
"border: 10px solid;\n"
"border-right: 0px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-color: rgb(70, 70, 70);\n"
"\n"
"")
        self.left.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.left.setScaledContents(True)
        self.left.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.left.setIndent(0)
        self.left.setObjectName("left")
        self.horizontalLayout_2.addWidget(self.left)
        self.right = QtWidgets.QLabel(parent=self.text_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right.sizePolicy().hasHeightForWidth())
        self.right.setSizePolicy(sizePolicy)
        self.right.setMinimumSize(QtCore.QSize(100, 0))
        self.right.setMaximumSize(QtCore.QSize(600, 16777215))
        self.right.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.right.setFont(font)
        self.right.setStyleSheet("padding-top: 8px;\n"
"padding-bottom: 8px;\n"
"padding-left: 0px;\n"
"\n"
"margin-left: -500px;\n"
"\n"
"border: 10px solid;\n"
"border-left: 0px;\n"
"border-top-right-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-color: rgb(70, 70, 70);\n"
"\n"
"background-color: rgb(255, 255, 255);")
        self.right.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.right.setScaledContents(False)
        self.right.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.right.setWordWrap(False)
        self.right.setIndent(0)
        self.right.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.right.setObjectName("right")
        self.horizontalLayout_2.addWidget(self.right)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.text_box)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(parent=Train)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout.addWidget(self.frame_3)
        self.right.setBuddy(self.text_box)

        self.retranslateUi(Train)
        QtCore.QMetaObject.connectSlotsByName(Train)

    def retranslateUi(self, Train):
        _translate = QtCore.QCoreApplication.translate
        Train.setWindowTitle(_translate("Train", "Form"))
        self.progress_bar.setFormat(_translate("Train", "%p%"))
        self.timer.setText(_translate("Train", "00:00"))
        self.left.setText(_translate("Train", "Пробел - СТАРТ "))
        self.right.setText(_translate("Train", "Esc - СТОП/Выход"))
